on: [push, pull_request]
name: CI
jobs:
  clippy_rustfmt:
    name: Lint & Format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - default
          - ssl-openssl
          - ssl-rustls
          - ssl-native-tls
    steps:
      - uses: actions/checkout@v5
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.features }}

      - name: Clippy
        run: cargo clippy --features ${{ matrix.features }}

      - name: Format
        run: cargo fmt -- --check

  test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - nightly
          - "1.98.1"
        features:
          - default
          - ssl-openssl
          - ssl-rustls
          - ssl-native-tls
    # nightly is allowed to drift/regress without failing the whole matrix
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    steps:
      - uses: actions/checkout@v5
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.rust }}-${{ matrix.features }}

      - name: Build
        run: cargo build --features ${{ matrix.features }}

      - name: Test
        run: cargo test --features ${{ matrix.features }}
